language: php
sudo: false
php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - 7.0
  - 7.1
install:
  - pear upgrade-all --nobuild --ignore-errors
  - pear install stream_var
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash
script:
  - phpunit --coverage-text tests
  - phpcs Net/
